# Generated by Django 2.1.5 on 2019-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleFolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
